[package]
name = "notifieru"
version = "0.1.0"
edition = "2021"

[dependencies]
minreq = { version = "2.12.0", features = [
  "https-rustls-probe",
  "urlencoding",
  "json-using-serde",
] }
serde_json = "1.0.132"
